### ISSUE TITLE
two more color gradients

### ISSUE THREAD

**Issue by moebiussurfing** [HankiDesign/awesome-dear-imgui#2]
hello, 
Thanks for this list!
I just wanted to share two gradient color editors:
https://github.com/CoolLibs/imgui_gradient
https://github.com/effekseer/ImGradientHDR

**Comment by TimoSalomaki** [comment]
Thanks a lot for the suggestions @moebiussurfing! I just added them to the list.

**Comment by moebiussurfing** [comment]
hey @HankiDesign 

I put some more cool stuff to be included if you like:

https://github.com/pearleascent/imgui-editor
https://github.com/cmdwtf/imgui_toggle
https://github.com/kem0x/ImTween
https://github.com/alanjfs/sequentity

**Comment by TimoSalomaki** [comment]
Thanks again @moebiussurfing, much appreciated! I've been busy lately so sorry for replying so late. I'll take a look at the projects you've linked here in the near future and add them if they're suitable.
